spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
management:
  security:
    enabled: false
 