spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    listener:
      concurrency: 2 
      max-concurrency: 2 
management:
  security:
    enabled: false
 